#include "const.hpp"
namespace ron {
ErrorList ERRORS = {
	{BADARGMNT, (Codepoint*)U"bad argument"},
	{BADARGMNT8, (Codepoint*)U"too many file descriptors"},
	{BADARGMNTb, (Codepoint*)U"a branch name must be a short name"},
	{BADARGMNTE, (Codepoint*)U"unrecognized extra arguments"},
	{BADARGMNTi, (Codepoint*)U"bad URL"},
	{BADARGMNTL, (Codepoint*)U"expect a Lamport UUID"},
	{BADARGMNTl, (Codepoint*)U"name is too long; limit: 10 Base64 chars"},
	{BADARGMNTR, (Codepoint*)U"RON variant not understood"},
	{BADARGMNTr, (Codepoint*)U"wrong/unrelated replica"},
	{BADARGMNTs, (Codepoint*)U"a form name must be a short name"},
	{BADARGMNTt, (Codepoint*)U"the buffer is too short"},
	{BADARGMNTU, (Codepoint*)U"argument not understood"},
	{BADARGMNTu, (Codepoint*)U"unknown command"},
	{BADARGMNTV, (Codepoint*)U"incorrect UUID version"},
	{BADARGMNTx, (Codepoint*)U"unrecognized extra arguments"},
	{BADRONBOX, (Codepoint*)U""},
	{BADRONBOXJ, (Codepoint*)U"the box must be joined to the previous one"},
	{BADCOMAND, (Codepoint*)U""},
	{BADFORMAT, (Codepoint*)U""},
	{BADFORMAT1, (Codepoint*)U"magic bytes don not match"},
	{BADFORMATa, (Codepoint*)U"wrong UUID type"},
	{BADFORMATB, (Codepoint*)U"branch id is up to 10 Base64 chars"},
	{BADFORMATb, (Codepoint*)U"UUID expected"},
	{BADPAGE, (Codepoint*)U""},
	{BADPAGE_E, (Codepoint*)U"a varint page must not be empty"},
	{BADPAGE_S, (Codepoint*)U"a varint must not span pages"},
	{BADPATH, (Codepoint*)U""},
	{BADPATH_p, (Codepoint*)U"the parent path is not in the repo"},
	{BADPATH_x, (Codepoint*)U"the path is already in the repo"},
	{BADRECORD, (Codepoint*)U""},
	{BADRECORD1, (Codepoint*)U"wrong size varint"},
	{BADRECORDB, (Codepoint*)U"box size is out of bounds"},
	{BADRECORDC, (Codepoint*)U"bad checkout log entry"},
	{BADRECORDD, (Codepoint*)U"invalid yarn declaration"},
	{BADRECORDd, (Codepoint*)U"box descriptor is out of range"},
	{BADRECORDF, (Codepoint*)U"incorrect filename format"},
	{BADRECORDl, (Codepoint*)U"missing log data"},
	{BADRECORDL, (Codepoint*)U"the limb is corrupted"},
	{BADRECORDO, (Codepoint*)U"op format does not match the pattern"},
	{BADRECORDr, (Codepoint*)U"a rough map value is shorter than expected"},
	{BADRECORDR, (Codepoint*)U"the rough map is corrupted"},
	{BADRECORDS, (Codepoint*)U"no spec in a RONv op"},
	{BADRECORDT, (Codepoint*)U"the index twig seems damaged"},
	{BADRECORDU, (Codepoint*)U"bad UTF-8"},
	{BADRECORDv, (Codepoint*)U"mismatching varint"},
	{BADRECORDV, (Codepoint*)U"the varint stream is corrupted"},
	{BADREPLY, (Codepoint*)U""},
	{BADSIZE, (Codepoint*)U""},
	{BADSTATE, (Codepoint*)U""},
	{BADSTATE_C, (Codepoint*)U"concurrent changes detected"},
	{BADSTATE_c, (Codepoint*)U"there are uncommitted changes"},
	{BADSTATE_F, (Codepoint*)U"unclosed frame"},
	{BADSTATE_O, (Codepoint*)U"already open"},
	{BADSTATE_R, (Codepoint*)U"failed to reach the root"},
	{BADSTATE_T, (Codepoint*)U"the branch is torn (the last recorded op is not local)"},
	{BADSTATE_o, (Codepoint*)U"operation is not supported"},
	{BADSTATE_x, (Codepoint*)U"invlid concurrent write"},
	{BADSTATE_t, (Codepoint*)U"the file is apparently touched"},
	{BADSTATE_w, (Codepoint*)U"not writable"},
	{BADSYNTAX, (Codepoint*)U""},
	{BADSYNTAXE, (Codepoint*)U"can not spread non-event ops"},
	{BADSYNTAXF, (Codepoint*)U"invalid float"},
	{BADSYNTAXI, (Codepoint*)U"invalid integer"},
	{BADSYNTAXi, (Codepoint*)U"malformed branch id"},
	{BADSYNTAXR, (Codepoint*)U"invalid RONt syntax"},
	{BADSYNTAXS, (Codepoint*)U"invalid RONt spread"},
	{BADSYNTAXU, (Codepoint*)U"invalid UUID syntax"},
	{BADSYNTAXJ, (Codepoint*)U"invalid JSON syntax"},
	{BADTYPE, (Codepoint*)U""},
	{BADUIDELT, (Codepoint*)U""},
	{BADUNICODE, (Codepoint*)U""},
	{BADUUID, (Codepoint*)U""},
	{ISECLIPSED, (Codepoint*)U"eclipsed by a concurrent value"},
	{ENDOFRAME, (Codepoint*)U"end of input"},
	{ENDOFRAME1, (Codepoint*)U"end of a FACT frame"},
	{ENDOFRAME2, (Codepoint*)U"end of a BLOB frame"},
	{ENDOFRAME3, (Codepoint*)U"end of a QUERY frame"},
	{ENDOFRAMEE, (Codepoint*)U"end of file or stream"},
	{ENDOFRAMEB, (Codepoint*)U"end of a blob"},
	{ERRNO, (Codepoint*)U""},
	{FAILDB, (Codepoint*)U""},
	{FAILEXEC, (Codepoint*)U""},
	{FAILEXEC_r, (Codepoint*)U"remote execution failed"},
	{FAILINOUT, (Codepoint*)U""},
	{FAILINOUTC, (Codepoint*)U"can not close a file?!"},
	{FAILINOUTc, (Codepoint*)U"can not create a file"},
	{FAILINOUTD, (Codepoint*)U"getcwd fails"},
	{FAILINOUTl, (Codepoint*)U"can not list a directory"},
	{FAILINOUTO, (Codepoint*)U"can not open a file"},
	{FAILINOUTR, (Codepoint*)U"read fails"},
	{FAILINOUTS, (Codepoint*)U"can not fsync"},
	{FAILINOUTW, (Codepoint*)U"write fails"},
	{FAILLOCK, (Codepoint*)U""},
	{FAILMERGE, (Codepoint*)U""},
	{FAILMMAP, (Codepoint*)U""},
	{FAILMMAP_U, (Codepoint*)U"can not unmap memory"},
	{FAILNAVBLK, (Codepoint*)U""},
	{FAILNET, (Codepoint*)U""},
	{FAILNOOBJ, (Codepoint*)U""},
	{FAILNOOP, (Codepoint*)U""},
	{FAILNOYARN, (Codepoint*)U"no such yarn"},
	{FAILNOYID, (Codepoint*)U"need a yarn id (non-zero)"},
	{FAILOBJGAP, (Codepoint*)U""},
	{FAILOPEN, (Codepoint*)U""},
	{FAILOPEN_1, (Codepoint*)U"can not open the file"},
	{FAILOPEN_P, (Codepoint*)U"fork() failed"},
	{FAILOPFMT, (Codepoint*)U""},
	{FAILOPFMT1, (Codepoint*)U"yarn object root must have RDT `yarn`"},
	{FAILOPFMTE, (Codepoint*)U"event id expected (YOLO)"},
	{FAILOPFMTO, (Codepoint*)U"zero yarn id is not allowed (except in @0-0-0)"},
	{FAILOPFMTR, (Codepoint*)U"root ref must be an RDT (short name)"},
	{FAILOPFMTr, (Codepoint*)U"yarn root is also an object root"},
	{FAILREF, (Codepoint*)U""},
	{FAILREF_E, (Codepoint*)U"home index 0 must be a root"},
	{FAILREF_H, (Codepoint*)U"reverse order of home indices"},
	{FAILREF_R, (Codepoint*)U"op's ref is not found"},
	{FAILREPET, (Codepoint*)U""},
	{FAILREPET1, (Codepoint*)U"the op was already seen"},
	{FAILREPET2, (Codepoint*)U"the yarn was already seen"},
	{FAILRESIZE, (Codepoint*)U"can not resize a file"},
	{FAILROOT, (Codepoint*)U""},
	{FAILVALUES, (Codepoint*)U""},
	{FAILVARINT, (Codepoint*)U""},
	{FAILYRNGAP, (Codepoint*)U""},
	{FAILZIP, (Codepoint*)U""},
	{NEEDARG, (Codepoint*)U""},
	{NEQFLOAT, (Codepoint*)U""},
	{NEQFRAMLEN, (Codepoint*)U""},
	{NEQID, (Codepoint*)U""},
	{NEQINT, (Codepoint*)U""},
	{NEQREF, (Codepoint*)U""},
	{NEQSTRING, (Codepoint*)U""},
	{NEQUUID, (Codepoint*)U""},
	{NEQVALCNT, (Codepoint*)U""},
	{NEQVALTYPE, (Codepoint*)U""},
	{NOACCESS, (Codepoint*)U""},
	{NOACCESS_r, (Codepoint*)U"the path is outside the repo"},
	{NOCOMMIT, (Codepoint*)U""},
	{NODATA, (Codepoint*)U"no more data available"},
	{BADSEAL, (Codepoint*)U"the sealing signature does not match the data"},
	{OLDSEAL, (Codepoint*)U"the old sealing signature matches"},
	{NODIR, (Codepoint*)U""},
	{NOSPACE, (Codepoint*)U""},
	{NOTAVAILB, (Codepoint*)U""},
	{NOTFOUND, (Codepoint*)U""},
	{NOTFOUND0a, (Codepoint*)U"no repo found"},
	{NOTFOUND0b, (Codepoint*)U"missing argument"},
	{NOTFOUND0C, (Codepoint*)U"no such checkout"},
	{NOTFOUND0d, (Codepoint*)U"not a directory"},
	{NOTFOUND0F, (Codepoint*)U"expected a FLOAT"},
	{NOTFOUND0f, (Codepoint*)U"file not found"},
	{NOTFOUND0I, (Codepoint*)U"expected an INT"},
	{NOTFOUND0L, (Codepoint*)U"limb not found"},
	{NOTFOUND0P, (Codepoint*)U"new path, no file created yet"},
	{NOTFOUND0p, (Codepoint*)U"path not found"},
	{NOTFOUND0x, (Codepoint*)U"peer not found"},
	{NOTFOUND0R, (Codepoint*)U"no such record"},
	{NOTFOUND0S, (Codepoint*)U"expected a STRING"},
	{NOTFOUND0T, (Codepoint*)U"not found in a trie"},
	{NOTFOUND0U, (Codepoint*)U"expected an UUID"},
	{NOTIMPLTD, (Codepoint*)U""},
	{NOTIMPLTDf, (Codepoint*)U"form unknown"},
	{NOTIMPLTDp, (Codepoint*)U"projection unknown"},
	{NOTIMPLTDP, (Codepoint*)U"protocol not implemented"},
	{NOTOK_C, (Codepoint*)U"the working copy has changes; stash or drop"},
	{NOTOPEN, (Codepoint*)U""},
	{NOTOPEN_b, (Codepoint*)U"no open branch"},
	{NOTOPEN_R, (Codepoint*)U"file not open for reading"},
	{NOTOPEN_W, (Codepoint*)U"file not open for writing"},
	{NOTREADY, (Codepoint*)U""},
	{NOTSAVED, (Codepoint*)U""},
	{OUTOMEMRY, (Codepoint*)U""},
	{OUTORANGE, (Codepoint*)U"out of range"},
	{OUTORANGEB, (Codepoint*)U"the position is greater than the branch size"},
	{OUTORANGEL, (Codepoint*)U"no such line"},
	{OUTORANGEl, (Codepoint*)U"the position is not in the log"},
	{OUTORANGEO, (Codepoint*)U"home index is not valid"},
	{OUTORANGER, (Codepoint*)U"root is reached, can not go further"},
	{SQLITE, (Codepoint*)U""},
	{WARNSHORT, (Codepoint*)U""},
};
}
